version: "3.7"

services:
  currencies:
    build: "./currencies" 
    ports:
      - 8081:8081
    volumes:
      - "./currencies/logs:/var/log/currencies"

  products:
    build: "./products" 
    ports:
      - 8082:8082
    volumes:
      - "./products/logs:/var/log/products"
      - "./products/data:/srv/products"      

  clients:
    build: "./clients" 
    ports:
      - 8083:8083
    volumes:
      - "./clients/logs:/var/log/clients"
      - "./clients/data:/srv/clients"

  cart:
    build: "./cart" 
    ports:
      - 8084:8084
    volumes:
      - "./cart/logs:/var/log/cart"
      - "./cart/data:/srv/cart"      
    depends_on:
      - clients
      - products  
      - currencies
    links:
      - clients
      - products
      - currencies

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - currencies
      - products
      - clients
      - cart