version: "3.7"

services:
  currencies:
    build: "./currencies" 
    ports:
      - 8081:8080
    volumes:
      - "./currencies/logs:/srv/server/logs"

  products:
    build: "./products" 
    ports:
      - 8082:8080
    volumes:
      - "./products/logs:/srv/server/logs"
      - "./products/data:/srv/server/data"      

  clients:
    build: "./clients" 
    ports:
      - 8083:8080
    volumes:
      - "./clients/logs:/srv/server/logs"
      - "./clients/data:/srv/server/data"

  cart:
    build: "./cart" 
    ports:
      - 8084:8080
    volumes:
      - "./cart/logs:/srv/server/logs"
      - "./cart/data:/srv/server/data"      
    depends_on:
      - clients
      - products  
      - currencies
    links:
      - clients
      - products
      - currencies

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - currencies
      - products
      - clients
      - cart