build:
	@echo " >> Building clients..." && cd clients && make build && cd ..
	@echo " >> Building currencies..." && cd currencies && make build && cd ..
	@echo " >> Building products..." && cd products && make build & cd ..
	@echo " >> Building cart..." && cd cart && make build && cd ..
all:
	@echo " >> Building clients..." && cd clients && make all && cd ..
	@echo " >> Building currencies..." && cd currencies && make all && cd ..
	@echo " >> Building products..." && cd products && make all & cd ..
	@echo " >> Building cart..." && cd cart && make all && cd ..

clean:
	@echo " >> Building clients..." && cd clients && make clean && cd ..
	@echo " >> Building currencies..." && cd currencies && make clean && cd ..
	@echo " >> Building products..." && cd products && make clean & cd ..
	@echo " >> Building cart..." && cd cart && make clean && cd ..