build:
	@cd clients && make build && cd ..
	@cd currencies && make build && cd ..
	@cd products/cart && make build && cd ..
	@cd cart && make build && cd ..
all:
	@cd clients && make clean && make all && cd ..
	@cd currencies && make clean && make all && cd ..
	@cd products/cart && make clean && make all && cd ..
	@cd cart && make clean && make all && cd ..

clean:
	@cd clients && make clean && cd ..
	@cd currencies && make clean && cd ..
	@cd products/cart && make clean && cd ..
	@cd cart && make clean && cd ..