FROM golang:latest

RUN mkdir -p /srv/server && \
    mkdir -p /srv/server/logs && \
    mkdir -p /srv/server/data   

WORKDIR /srv/server

COPY bin/linux-amd64/service /srv/server/service
COPY etc/config.json /srv/server/config.json

EXPOSE 8080

ENTRYPOINT ["/srv/server/service", "/srv/server/config.json"]